openapi: 3.2.0
info:
  title: Keystone Membership Fees API
  version: v12
  description: This is the endpoint description of Keystone API.
servers:
- url: https://api.sandbox.autoenrolment.co.uk
- url: /
tags:
- name: MembershipFees
paths:
  /companies/{company_id}/membership_fees:
    get:
      summary: Companies/MembershipFees/Get
      tags:
      - MembershipFees
      security:
      - oAuth2:
        - employee
      parameters:
      - name: company_id
        in: path
        required: true
        example: 1205
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                employee_amount: 1.25
              schema:
                $ref: '#/components/schemas/response_membership_fees'
        '401':
          description: Unauthorized
components:
  schemas:
    response_membership_fees:
      type: object
      properties:
        employee_amount:
          type:
          - number
          - 'null'
          format: float
  securitySchemes:
    oAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://id.sandbox.autoenrolment.co.uk/oauth/authorize
          tokenUrl: https://id.sandbox.autoenrolment.co.uk/oauth/token
          scopes:
            customer: 'Manage the customer''s company.

              - Create postponements

              - Create and import contributions

              - Edit company details

              - Add and edit employees'
            user: 'Manage all companies linked to the user''s adviser.

              - Manage adviser details

              - Add and edit adviser''s users

              - Create and import contributions for any company managed by the adviser'
            employee: 'Manage the employee account.

              - List employee contributions

              - Edit employee details and preferences'
x-samples-languages:
- curl
x-proxy-enabled: false
